# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:15
    restart: always
    container_name: trailed_pg_db
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: gyuha
      POSTGRES_PASSWORD: rbgksla
      POSTGRES_DB: trailed
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
    ports:
      - '8080:8080'
    privileged: true
    user: root
